version: "3.8"

x-common-env: &common-env
  FRONTEND_HOST: ${DOCKER_IP:-172.17.0.1}

services:
  app: &app
    build:
      context: .dockerdev
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        UBUNTU_VERSION: ${UBUNTU_VERS}
    image: ${PROJECT_NAME}:${ENV_VERS}
    tmpfs:
        - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    environment:
      <<: *common-env
      FLASK_ENV: ${FLASK_ENV:-development}
      REDIS_URL: redis://redis:6379/
      REDIS_TRAINING_QUEUE: ${REDIS_TRAINING_QUEUE}
      REDIS_PREDICTION_QUEUE: ${REDIS_PREDICTION_QUEUE}
      REDIS_FETCH_QUEUE: ${REDIS_FETCH_QUEUE}
    volumes:
      - .:/${PROJECT_NAME}:cached
    depends_on:
      redis:
        condition: service_healthy

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '5000:5000'

  flask:
    <<: *backend
    command: flask run --host=0.0.0.0
    ports:
      - '5000:5000'

  training_worker:
    <<: *backend
    command: flask start_worker

  prediction_worker:
    <<: *backend
    command: flask start_worker prediction

  pytest:
    <<: *backend
    command: python -m pytest
    environment:
      <<: *common-env
      FLASK_ENV: test

  redis:
    image: redis:${REDIS_VERS}-alpine
    ports:
      - 6379
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30


volumes:
  redis:
