version: "3.8"

services:
  app: &app
    build:
      context: .dockerdev
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: ${PROJECT_NAME}
    image: ${PROJECT_NAME}:${ENV_VERS}
    tmpfs:
        - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
    volumes:
      - .:/${PROJECT_NAME}:cached

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '5000:5000'

  flask:
    <<: *backend
    command: flask run --host=0.0.0.0
    ports:
      - '5000:5000'

  pytest:
    <<: *backend
    command: python -m pytest
    environment:
      - FLASK_ENV=test
